### ISSUE TITLE
注意力模块添加后预训练模型加载问题以及模块加载位置

### ISSUE THREAD

**Issue by ghostbreaken** [pprp/pytorch-cifar-model-zoo#1]
如果加了注意力模块，是不是pytorch官网下载的预训练模型就不能用了？得自己重新训练？怎么加注意力机制可以不用重新训练模型呢？
关于resnet50和inceptionv3加入注意力模块应该怎么加呢？是在卷积输入的最后一层嘛？

**Comment by pprp** [comment]
@ghostbreaken 是可以加载的，因为pytorch中模型的加载是根据key:value，如果用原来的backbone，原始的key是不会改变的，但是由于增加了注意力模块，会导致增加一些新的key。这样就很容易处理了，在加载的过程中根据key来加载，遇到未定义的key就跳过即可。

注意力模块一般来说建议放在靠后的层，因为计算量比较大，如果在靠前层中添加带来的开销比较大。

**Comment by pprp** [comment]
@ghostbreaken 近期做了新的实验，将结果反馈给你。pytorch下载的预训练模型是能够加载的，只不过attention部分的权重会自动跳过，因此attention模块的权重是随机初始化的。
以ResNet50为例，将加载了注意力的模型称为ResNet50_Attention, 那么对于分类任务来说，建议是在ImageNet上从头开始训练加了注意力模块的模型，即从头开始训练ResNet50_Attention。

从下游任务的反馈来说，如果需要使用ResNet50_Attention作为Backbone，那么建议将ImageNet上预训练完成的模型加载，而不是加载ResNet50的权重，finetune Attention的方式（这样的处理方式会带来性能上较大的Drop）。
