### ISSUE TITLE
有关内存和显存占用的问题

### ISSUE THREAD

**Issue by missbook520** [pprp/pytorch-cifar-model-zoo#3]
您好，我在训练过程中发现您的实现对于cpu和gpu有较大的要求，我的内存是16g，gpu是6g，数据集是自己的数据集，一共400张左右，大小在200*200左右，数据预处理阶段将其resize到224*224，bs设置为4，但是我使用resnet20时跑到80左右的epoch就会报cpu内存不足的错误，而使用shake_resnet26_2x64d模型会直接报显卡内存不足的错误，请问您能指点一下吗？

**Comment by pprp** [comment]
感谢关注，这个库主要是针对CIFAR数据集进行调参和测试，而CIFAR数据集由于分辨率比较小（仅32x32），因此可以使用大的batch进行训练。当数据集分辨率较高的时候，对显存和内存的要求也会相应以N^2倍（N=224/32）提高。

1. cpu内存不足的错误，主要受batch size和分辨率的影响，CPU需要一定的内存完成数据预处理的任务，如果内存不足，可以降低batch size大小，或者降低分辨率大小，同时设置num_workers=0,能够一定程度上缓解对内存需求。
2. 显存不足也是正常的，因为shake_resnet26_2x64d是一个比较宽的模型，通道数比较多，对显存需求比较大，可以使用apex混合精度的方法来降低显存占用，配合降低batch size大小。

如果对batch size大小有要求，不能过小，可以采用accumulate gradient的方式，即每隔N个大小为B的Batch Size进行一次反向传播，这样近似的batch size=B*N
