### ISSUE TITLE
关于mobilevit的问题

### ISSUE THREAD

**Issue by Jerryme-xxm** [pprp/pytorch-cifar-model-zoo#4]
您好，请问您是将一样尺度的mobilevit试验于cifar了吗？

我看到您Mobilevit的表格那里，mobilevits的weight都接近20M了。
然而mobilevit原作者将mobilevit用于256*256的imagenet分类任务，也只有3M左右。原网络里有32倍的尺度下降，勉强可以不改结构跑cifar，但是为什么weight会增加呢，我感觉很疑惑。

如果可以，希望您可以解答。

**Comment by pprp** [comment]
您好，我的表格中统计的并非是params，而是权重占用的空间大小。

**Comment by Jerryme-xxm** [comment]
我明白了
谢谢您的解答
